"""Structured create/edit/delete data-flow contracts for the `frontend_forms`
generation stage.

Owner: `engineering.factory`. Convergence fix (real repository evidence:
golden-work-113/119/122/125, the identical `StudentForm`-shared-component
callback-arity defect recurring across 4 independent real qwen2.5-coder:14b
runs, the last exhausting all 4 real bounded attempts outright). Prose
guidance describing the correct shape was already added to `frontend_forms`'s
own stage rule (`STAGED_GENERATION_STAGES.md#9`) after golden-work-113/115
and golden-work-119 -- the model still reproduced the identical class twice
more. `product_ux_spec.json` itself only ever declared that an "edit" action
exists (`_UxFormSpec.fields` is a flat `tuple[str, ...]`, no route/param/
signature information, and nothing stops a real model from listing the
route's own identifier as though it were a user-entered form field --
golden-work-125's own real `product/ux_spec.json` did exactly this: `"fields":
["id", "name", "email"]`). Every other structured fact the model would need
-- the real backend update signature's exact parameter order, the route path,
which field is route-supplied rather than user-entered -- was left for the
model to re-derive from raw prior-file source on every attempt, in prose,
sharing space with unrelated concerns (delete controls, confirmation,
success markers, route-shadowing) in one dense paragraph.

This module builds that missing structured fact set once, deterministically,
from real data already generated by earlier stages (`product_ux_spec`,
`frontend_client`) -- not guessed, not modeled from the requirement text a
second time. `stage_prompting.py` includes its result as its own
`mutation_contracts` field for `frontend_forms` specifically, alongside (not
instead of) the stage's own prose rule.
"""

from __future__ import annotations

import json
from collections.abc import Mapping

from arkali.engineering.factory.frontend_js_semantics import _function_parameters

#: Field names in `product_ux_spec.json`'s own `forms[].fields` that name the
#: route's own identifier, not something a real user types into the form --
#: golden-work-125's own real spec listed "id" this way. Never surfaced as a
#: real form field in the structured contract below.
_ROUTE_IDENTIFIER_FIELD_NAMES = frozenset({"id"})
#: (declared action, real client-function verb prefix) -- the exact,
#: consistently observed real naming convention across every evidenced
#: candidate this session (`createStudent`, `updateStudent`, `deleteStudent`,
#: `createPayment`, ...).
_ACTION_VERBS: tuple[tuple[str, str], ...] = (
    ("create", "create"), ("edit", "update"), ("delete", "delete"),
)


def _singularize(module_name: str) -> str:
    """The exact naive rule every real evidenced candidate's own client
    function naming already follows: strip one trailing "s" (`students` ->
    `Student`, `payments` -> `Payment`), title-case the rest. No attempt at
    real English pluralization beyond this -- guessing further risks a
    wrong match more than the naive rule risks missing one."""
    stripped = module_name[:-1] if module_name.endswith("s") else module_name
    return stripped[:1].upper() + stripped[1:] if stripped else stripped


def _action_contract(
    action: str, verb: str, module_name: str, client_source: str,
) -> dict[str, object] | None:
    function_name = f"{verb}{_singularize(module_name)}"
    params = _function_parameters(function_name, client_source)
    if params is None:
        return None
    entry: dict[str, object] = {"client_function": function_name, "signature": list(params)}
    if action in ("edit", "delete"):
        entry["route"] = f"/{module_name}/{action}/:id"
        entry["route_param"] = "id"
    return entry


def _parse_ux_spec(ux_spec_json: str) -> dict[str, object] | None:
    try:
        spec = json.loads(ux_spec_json)
    except (ValueError, TypeError):
        return None
    return spec if isinstance(spec, dict) else None


def _module_form_fields(module: Mapping[str, object]) -> list[str]:
    raw_fields: list[str] = []
    for form in module.get("forms", None) or []:
        if isinstance(form, dict):
            raw_fields.extend(f for f in (form.get("fields", None) or []) if isinstance(f, str))
    return [f for f in raw_fields if f not in _ROUTE_IDENTIFIER_FIELD_NAMES]


def _module_actions(
    module_name: str, declared_actions: set[object], client_source: str,
) -> dict[str, object]:
    actions: dict[str, object] = {}
    for action, verb in _ACTION_VERBS:
        if action not in declared_actions:
            continue
        entry = _action_contract(action, verb, module_name, client_source)
        if entry is not None:
            actions[action] = entry
    return actions


def _module_contract(module: object, client_source: str) -> dict[str, object] | None:
    if not isinstance(module, dict):
        return None
    module_name = module.get("name")
    if not isinstance(module_name, str) or not module_name:
        return None
    actions = _module_actions(module_name, set(module.get("actions", None) or []), client_source)
    if not actions:
        return None
    return {"module": module_name, "actions": actions, "form_fields": _module_form_fields(module)}


def _build_mutation_contracts(
    ux_spec_json: str, client_source: str,
) -> list[dict[str, object]]:
    """One structured entry per `product_ux_spec` module that declares a
    create, edit, or delete action AND whose corresponding real client
    function can be found by name in `client_source` -- never fabricated
    for an action whose real client function does not actually exist yet.
    Each entry:
        {"module": str,
         "actions": {"create"|"edit"|"delete": {
             "client_function": str, "signature": [param, ...],
             "route": str,          # edit/delete only
             "route_param": str,    # edit/delete only -- never a form field
         }},
         "form_fields": [str, ...]}  # route identifiers excluded
    Returns `[]` for anything that cannot be parsed as the real UX spec
    JSON shape -- silent, not a hard failure, the same posture every other
    stage-input derivation in this pipeline already takes.
    """
    spec = _parse_ux_spec(ux_spec_json)
    if spec is None:
        return []
    contracts = (
        _module_contract(module, client_source) for module in spec.get("modules", None) or []
    )
    return [contract for contract in contracts if contract is not None]


def _mutation_contracts_for_stage(
    declaration_inputs: tuple[str, ...], visible_files: Mapping[str, str],
) -> list[dict[str, object]] | None:
    """`None` for any stage that does not declare BOTH `product_ux_spec`
    and `frontend_client` as real inputs -- today, exactly `frontend_forms`
    -- so this never applies to a stage with no real create/edit/delete
    concern at all."""
    if "product_ux_spec" not in declaration_inputs or "frontend_client" not in declaration_inputs:
        return None
    ux_spec_json = next(
        (content for path, content in visible_files.items() if path.endswith("ux_spec.json")), None,
    )
    client_source = "\n".join(
        content for path, content in visible_files.items()
        if path.startswith("frontend/src/") and "client" in path.lower()
    )
    if ux_spec_json is None or not client_source:
        return []
    return _build_mutation_contracts(ux_spec_json, client_source)
